- src/components/Navigation/Sidebar.vue
- src/router/index.js
- src/util/tableOfContent.js
- src/views/Help.vue
does not have any css atm, so it looks ugly as hell
> Redesign help

- src/components/ItemRow.vue
- src/components/Navigation/Sidebar.vue
- src/components/Navigation/SiteHeader.vue
- src/components/widgets/WidgetsKeyResultHome.vue
- src/store/actions/set_user.js
> Redesign item admin

- functions/automatedKeyResults.js
- src/components/Modal.vue
- src/components/Navigation/Sidebar.vue
- src/components/widgets/WidgetKeyResultNotes.vue
- src/components/widgets/WidgetTeam.vue
- src/components/widgets/WidgetsItemHome.vue
- src/components/widgets/WidgetsKeyResultHome.vue
- src/main.js
- src/migrate/index.js
- src/store/actions/set_active_objective.js
- src/store/index.js
- src/styles/_forms.scss
- src/util/PieChart/pie-helpers.js
- src/views/Admin/CreateDepartment.vue
- src/views/Admin/CreateOrganization.vue
- src/views/Admin/CreateProduct.vue
- src/views/Admin/components/AddUsers.vue
- src/views/Admin/components/EditUser.vue
- src/views/ItemAdmin/ItemAdminGeneralDepartment.vue
- src/views/ItemAdmin/ItemAdminGeneralOrganization.vue
- src/views/ItemAdmin/ItemAdminGeneralProduct.vue
- src/views/ItemAdmin/ItemAdminKeyResult.vue
- src/views/ItemAdmin/ItemAdminObjective.vue
- src/views/ItemAdmin/ItemAdminPeriod.vue
- src/views/KeyResultHome.vue
- src/views/RequestAccess.vue
- src/views/User.vue
The part which calls the cloud functions for the first time is not yet implemented. Ill fix that for the next PR, getting this out first
> Redesign automated keyres

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- README.md
- firebase-export-metadata.json
- package-lock.json
- package.json
- public/help.md
- src/components/ItemRow.vue
- src/components/KpiLink.vue
- src/components/Kpis.vue
- src/components/widgets/WidgetChildItems.vue
- src/components/widgets/WidgetKeyResultNotes.vue
- src/components/widgets/WidgetMissionStatement.vue
- src/components/widgets/WidgetObjectiveDetails.vue
- src/config/kpiTypes.js
- src/db/Objective/Objective.js
- src/db/Period/Period.js
- src/locale/i18n.js
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/store/actions/set_user.js
- src/util/findSlugAndRedirect.js
- src/views/Admin/CreateDepartment.vue
- src/views/Admin/CreateOrganization.vue
- src/views/Admin/CreateProduct.vue
- src/views/KeyResultHome.vue
- src/views/User.vue
- tests/firebase-export-metadata.json
- English locale
- Store language preference on user
- Change language preference on profile page
- Markdown support on mission statements and key result notes
- Force order of KPIs + include non-existent KPIs on ItemHome
- Fix issue with findSlugAndRedirect-method - returns redirect and increased delay
- Add defaultPreferences on user if not existing (simplifies mock data creation)
- Remove misplaced markup on objective details widget
- Add missing translations
- Replaced 'deleted' with 'archived' in toaster
- Automatically archives related objectives and key results when archiving periods and objectives
- Improved Google Sheets integration guide on help page
- Display startValue if no currentValue is set on key result home view
> Release v2.0.0-beta.2

- CHANGELOG.md
- package-lock.json
- package.json
- src/main.js
…ItemAdminOKRs mount/unmount each time
> Release v2.1.2

- CHANGELOG.md
- firestore.rules
- package-lock.json
- package.json
- src/router/router-guards/itemAdmin.js
fix(rbac): users were not allowed to update their own products/departments/organizations
> Release 2.3.1

- CHANGELOG.md
- package.json
- src/components/AddKPIModal.vue
- src/components/FormComponent.vue
- src/styles/_buttons.scss
- src/styles/_forms.scss
> Change label and button color in AddKPIModal.

- common/db/Collection.js
- common/db/KeyResultsCollection.js
- common/db/ObjectivesCollection.js
- common/db/utils/booleanInCondition.js
- src/components/widgets/ObjectiveProgression.vue
Display key results on hover.
TODO: Add styling.
> Display objective ker results on hover.

- src/components/DashboardResultIndicatorsSection.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/util/downloadFile.js
Add option to download raw progress data in CSV.
> Add CSV download option

- src/components/KeyFigure.vue
> Fix styling for key figures

- src/components/DashboardPeriodSelector.vue
- src/components/DashboardResultIndicatorsSection.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/util/LineChart/index.js
- src/views/KeyResultHome.vue
- src/views/KpiHome.vue
Add an option in the result indicator plot to show all the history from the beginning of measurements until today.
Also did a bit of refactoring and cleanups along the way.
> Add option for showing history from the beginning

- src/components/DashboardPeriodSelector.vue
- src/components/DashboardResultIndicatorsSection.vue
- src/components/IndicatorTooltip.vue
- src/components/ItemRow.vue
- src/config/kpiTypes.js
- src/util/LineChart/index.js
- src/util/LineChart/linechart-helpers.js
- src/util/LineChart/symbols.js
- src/views/KpiHome.vue
* Formatting of tooltip values based on type
* Comment icons should not be included in graph export
* Minor style tweaks
> Format result indicator tooltip values

- src/components/widgets/WidgetProgressHistory.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/views/KeyResultHome.vue
- src/views/KpiHome.vue
~~Depends on https://github.com/oslokommune/okr-tracker/pull/403.~~
Shared component, aligned design.
> Consolidate progress history tables

- firestore.rules
- src/components/FormComponent.vue
- src/components/KeyResultModal.vue
- src/components/modals/ModalWrapper.vue
- src/components/modals/ProgressModal.vue
- src/components/widgets/WidgetProgressHistory.vue
- src/components/widgets/WidgetProgressHistory/UserLink.vue
- src/components/widgets/WidgetProgressHistory/WidgetProgressHistory.vue
- src/db/Progress/Progress.js
- src/db/common/methods/validateCreateProps.js
- src/db/common/methods/validateUpdateProps.js
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/styles/_modal.scss
- src/views/KeyResultHome.vue
- src/views/KpiHome.vue
> Allow editing of KPI and key result historic progress values

- src/components/DashboardResultIndicatorsSection.vue
- src/util/downloadPng.js
- src/util/format.js
> Add title and period to graph export (PNG)

- src/components/modals/AddKPIModal.vue
- src/components/modals/KeyResultModal.vue
- src/components/modals/ModalWrapper.vue
- src/components/modals/ProfileModal.vue
- src/components/modals/ProgressModal.vue
- src/components/widgets/WidgetKeyResultDetails.vue
- src/components/widgets/WidgetObjectiveDetails.vue
- src/components/widgets/WidgetProgressHistory/WidgetProgressHistory.vue
- src/components/widgets/WidgetTeam/WidgetTeam.vue
- src/styles/_modal.scss
Roughly align styling across all current modals.
> Align modal styling

- .eslintrc.js
Disable two ESLint rules that are causing more noise than they do good.
> Calm down, ESLint

- src/components/FormComponent.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/styles/_admin.scss
- src/styles/_forms.scss
- src/views/ItemAdmin/ItemAdminKPI.vue
> Copiable KPI curl command

- README.md
- functions/api/helpers.js
- functions/api/routes/kpi.js
- functions/api/validators.js
- public/openapi/v1.2.0.yaml
- src/views/Api.vue
* Only a single daily progression value is now enforced
* Adds new API endpoints for updating and deleting KPI progression values
> Allow only daily KPI measurement values: API (1/2)

- src/util/LineChart/index.js
Use the `nice` d3 domain function on line chart y axes. This function attempts to make the domain extremas "nice" by looking at the data (e.g. it finds that a nice domain for [0.201479…, 0.996679…] is [0.2, 1.0]).
> Nicen line chart y axis domain

- firestore.rules
- src/components/DashboardResultIndicatorsSection.vue
- src/components/FormComponent.vue
- src/components/modals/KPIProgressModal.vue
- src/components/modals/ModalWrapper.vue
- src/components/modals/ProgressModal.vue
- src/components/widgets/WidgetProgressHistory/WidgetProgressHistory.vue
- src/db/Kpi/Progress/Progress.js
- src/db/Kpi/Progress/index.js
- src/db/Kpi/Progress/props.js
- src/db/Progress/Progress.js
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/styles/_modal.scss
- src/views/KpiHome.vue
* Only a single daily progression value is now enforced
* Updates the frontend to account for these changes, e.g. the modal for editing values:
> Allow only daily KPI measurement values: Frontend (2/2)

- src/components/modals/ModalWrapper.vue
- src/components/modals/ProgressModal.vue
- src/styles/_modal.scss
Somewhat ...
* ... increased modal padding
*  ... decrease footer margin (top)
> Adjust modal padding

- src/components/modals/KPIProgressModal.vue
- src/components/modals/KeyResultModal.vue
- src/components/modals/ProgressModal.vue
- src/db/Kpi/Progress/Progress.js
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/views/KeyResultHome.vue
- src/views/KpiHome.vue
> Allow manually adding KPI progression value

- src/styles/_admin.scss
- src/views/ItemAdmin/ItemAdminGeneral.vue
- src/views/ItemAdmin/ItemAdminKPI.vue
- src/views/ItemAdmin/ItemAdminKPIs.vue
First step towards redesing the KPI admin panel.
> Clean up item admin form components

- package-lock.json
- package.json
Bump `swagger-ui` to be able to upgrade vulnerable sub-dependencies.
> Bump `swagger-ui`

- src/components/generic/collapse/CollapseContainer.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/styles/main.scss
- src/styles/ods/ods-badge.scss
- src/views/ItemAdmin/ItemAdminKPI.vue
- src/views/ItemAdmin/ItemAdminKPIs.vue
Based on https://github.com/oslokommune/okr-tracker/pull/476 (and will be rebased after merge).
> Use collapsibles for KPIs in admin

- src/components/DashboardResultIndicatorsSection.vue
- src/util/LineChart/index.js
- src/util/kpiHelpers.js
~~Depends on https://github.com/oslokommune/okr-tracker/pull/486 (this PR will be rebased after it has been merged).~~
> Pad y axes

- functions/kpi/fetchKpiData.js
- src/components/forms/KpiAdminForm.vue
- src/components/generic/form/buttons/Btn.vue
- src/components/modals/AddKPIModal.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/styles/_forms.scss
- src/views/ItemAdmin/ItemAdminKPI.vue
* Aligned with recent changes, i.e. allowing manual KPI progress updates
* Allow usage of both the Google Sheets and API integration
* ~~Based on https://github.com/oslokommune/okr-tracker/pull/477 (and to be rebased after merge)~~
> Reorganized KPI admin form

- src/views/ItemAdmin/ItemAdminOKRs.vue
> Order OKR periods by date and objectives and key results by name in admin panel

- src/components/generic/collapse/CollapseContainer.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/styles/_admin.scss
- src/views/ItemAdmin/ItemAdminKPI.vue
> Show KPI state indicators in admin panel

- package-lock.json
- package.json
Upgrade `firebase-tools`, mainly for security updates in its sub-dependencies.
> Bump `firebase-tools`

- src/components/DashboardDepartmentInfoBox.vue
- src/components/KPIs.vue
- src/components/KpiCard.vue
- src/components/widgets/ObjectiveProgression.vue
- src/components/widgets/WidgetDashboardEntry.vue
- src/styles/_forms.scss
- src/styles/_modal.scss
- src/styles/_tooltip.scss
- src/styles/ods/ods-badge.scss
- src/util/LineChart/index.js
- src/views/Dashboard/DashboardSection.vue
- src/views/ItemAdmin/ItemAdminKPI.vue
- src/views/KpiHome.vue
Clean out accumulated lint to prepare the merge to `develop`.
> Clean out lint

- src/components/FormComponent.vue
- src/components/forms/KpiAdminForm.vue
- src/db/Kpi/props.js
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/util/kpiHelpers.js
- src/views/ItemAdmin/ItemAdminKPIs.vue
> Add update frequency field to KPI form

- src/components/forms/KpiAdminForm.vue
- src/components/forms/partials/GoogleSheetsFormGroup.vue
- src/views/ItemAdmin/ItemAdminKeyResult.vue
* ~~Based on https://github.com/oslokommune/okr-tracker/pull/507~~
> Reusable Google Sheets form group

- package-lock.json
- package.json
Eliminate vulnerable sub-dependencies at the same time.
> Remove unused `@firebase/rules-unit-testing` lib

- CHANGELOG.md
Update the changelog with stuff from after the previous release up until today.
> Get the changelog up to speed

- CHANGELOG.md
Amend the changelog with the fix that was made in 3fb6695c8ba49dff7fcf3557883bf8ced8f59129.
> Amend changelog for 3fb6695c

- .github/workflows/deploy-prod.yml
- .github/workflows/pipeline.yml
> Pass all required secrets when triggered as reusable workflow

- CHANGELOG.md
- src/components/DashboardResultIndicatorsSection.vue
> Show all measurements by default for result indicators

- src/components/forms/KpiAdminForm.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
Move it to the bottom of the form and update its help text.
> Tweak KPI update frequency input field

- src/components/modals/KPIProgressModal.vue
- src/styles/_alerts.scss
- src/styles/main.scss
* [ODS Alert](https://designsystem.oslo.kommune.no/latest/komponenter/alert/index)
* [ODS Colors](https://designsystem.oslo.kommune.no/latest/profil/colors)
> Simplify and align alert styles with ODS

- src/styles/_admin.scss
- src/views/ItemAdmin/ItemAdminKPI.vue
Purge the green/gray/orange status bars on the KPI admin page. The red bar indicating an error in the Google Sheets connection is kept for now.
> Purge the KPI status bars

- CHANGELOG.md
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
> Rename heading and admin tab for KPIs to "Measurements"

- CHANGELOG.md
- src/components/DashboardResultIndicatorsSection.vue
- src/components/modals/EditGoalsModal.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/styles/main.scss
Statustag:
- når det ikke er noen endring i perioden vises teksten 'ingen endringEr på vei!
- når verdien er større enn null skal man prefikse med '+Er på vei!
- når måleenheten er prosent skal man vise prosentvis økning
- når måleenheten ikke er prosent skal man vise økningen som den er
Måltag:
- Vise mål uten noen utregning
> Added missing plus-sign and changed colors in tag

- src/components/FormComponent.vue
- src/components/UserProfileMenu.vue
- src/components/forms/KpiAdminForm.vue
- src/components/forms/UserProfileForm.vue
- src/components/modals/ProfileModal.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
Depends on https://github.com/oslokommune/okr-tracker/pull/579
> Reusable user profile form

- package-lock.json
- package.json
- src/components/ContentLoader/ContentLoaderItem.vue
- src/components/DashboardPeriodSelector.vue
- src/components/DashboardResultIndicatorsSection.vue
- src/components/EmptyState.vue
- src/components/ItemRow.vue
- src/components/KeyResultRow.vue
- src/components/TabList.vue
- src/components/UserProfileMenu.vue
- src/components/widgets/WidgetKeyResultDetails.vue
- src/components/widgets/WidgetObjectiveDetails.vue
- src/components/widgets/WidgetProgressHistory/WidgetProgressHistory.vue
- src/components/widgets/WidgetTeam/RoleMembers.vue
- src/styles/_admin.scss
- src/styles/_alerts.scss
- src/styles/_buttons.scss
- src/styles/_forms.scss
- src/styles/_miller.scss
- src/styles/_range-slider.scss
- src/styles/_tooltip.scss
- src/styles/main.scss
- src/styles/ods/ods-badge.scss
- src/util/LineChart/linechart-helpers.js
- src/util/downloadPng.js
- src/views/Admin/components/AdminAccessRequests.vue
- src/views/Dashboard/DashboardHome.vue
- src/views/ItemAdmin/ItemAdminKPI.vue
- src/views/ItemAdmin/ItemAdminOKRs.vue
Merge our existing color palette with the colors from Punkt. A handful of the colors were too unique to us to find a fitting mapping to a Punkt colors, so those have been kept around for now.
> Use Punkt colors

- src/components/FormComponent.vue
- src/views/ItemAdmin/ItemAdminGeneral.vue
- src/views/ItemAdmin/ItemAdminKeyResult.vue
- src/views/ItemAdmin/ItemAdminObjective.vue
Known, existing bug in these forms: route changes on `changedObjective` (key results) and `changedPeriod` (objectives) does not seem to work correctly. Fixed separately.
> Unified form validation for admin OKR forms

- CHANGELOG.md
- README.md
- src/config/firebaseConfig.js
Fjernet referansene til GA-id-en i firebase config, og fjernet initialiseringen av firebase.analytics()
> Removed google analytics connection

- src/views/ItemAdmin/ItemAdminKeyResult.vue
- src/views/ItemAdmin/ItemAdminOKRs.vue
- src/views/ItemAdmin/ItemAdminObjective.vue
- src/views/ItemAdmin/ItemAdminPeriod.vue
Fixes some bugs in the miller component, but there are still some remaining. These components are however to be replaced in the near future.
> Fix (some) bugs in the OKR admin panel

- CHANGELOG.md
- src/components/widgets/WidgetTeam/WidgetTeam.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/router/index.js
- src/router/router-guards/itemAdmin.js
- src/views/Forbidden.vue
- src/views/NotFound.vue
> Improved error handling for item admin and prettified error page views

- CHANGELOG.md
- src/components/ProgressUpdateAPIExample.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/views/ItemAdmin/ItemAdminKeyResult.vue
SSIA. La inn en liten link til API-dokumentasjonen, nedenfor Curl-eksempelet.
> Added contextual link to API documentation

- CHANGELOG.md
- src/components/DashboardResultIndicatorStatistics.vue
- src/components/DashboardResultIndicatorsSection.vue
- src/components/IconAlertSuccess.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/util/format.js
- src/util/index.js
> Result indicator stats reflects current period + checkmark icon for reached goals

- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
Made obsolete in 4bbf067d14e41c3189ac5daa08f27138a37e2483.
> Remove unused translation

- functions/package-lock.json
- package-lock.json
Apply `npm audit fix` to address security issues that don't require special attention.
> Apply `npm audit fix`

- src/App.vue
- src/components/ContentLoader/ContentLoaderItemAdminOKRDetails.vue
- src/components/DashboardPeriodSelector.vue
- src/components/DashboardResultIndicatorsSection.vue
- src/components/EmptyState.vue
- src/components/ItemRow.vue
- src/components/ProgressBar.vue
- src/components/TabList.vue
- src/components/UserProfileMenu.vue
- src/components/modals/EditGoalsModal.vue
- src/components/widgets/WidgetTeam/RoleMembers.vue
- src/styles/_admin.scss
- src/styles/_buttons.scss
- src/styles/_forms.scss
- src/styles/_widgets.scss
- src/styles/main.scss
- src/views/Admin/components/AdminItems.vue
- src/views/Admin/components/AdminUsers.vue
- src/views/Help.vue
- src/views/ItemAdmin/ItemAdminKPI.vue
- src/views/ItemAdmin/ItemAdminKeyResult.vue
- src/views/ItemAdmin/ItemAdminOKRs.vue
- src/views/ItemAdmin/ItemAdminObjective.vue
- src/views/ItemAdmin/ItemAdminPeriod.vue
- src/views/KeyResultHome.vue
- src/views/Login.vue
Replace the remaining non-Punkt CSS color variables with their nearest matches from the Punkt color palette.
> Get rid of non-Punkt color definitions

- functions/package-lock.json
Apply `npm audit fix` in `functions/` to address security issues that don't require special attention.
> Apply `npm audit fix` in `functions/`

- CHANGELOG.md
- src/util/LineChart/index.js
- src/util/LineChart/linechart-helpers.js
> Remove the gradient filler from the line chart

- src/components/TabList.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/styles/main.scss
- src/views/Item/ItemMeasurements.vue
- src/views/Item/ItemOKRs.vue
- src/views/KeyResultHome.vue
- src/views/KpiHome.vue
- src/views/ObjectiveHome.vue
First steps toward redesigning OKR-related views (including KPIHome). Removes the non-Punkt gradient.
> Unified layout for OKR views

- src/components/KeyResultRow.vue
- src/components/ObjectiveRow.vue
- src/components/ProgressBar.vue
- src/views/Item/ItemOKRs.vue
- src/views/ObjectiveHome.vue
Removed drop shadows and minor style tweaks.
> Adjust OKR listing styling to be more Punkt-ish

- src/components/KeyResultRow.vue
- src/components/ObjectiveRow.vue
- src/components/ProgressBar.vue
- src/components/widgets/WidgetKeyResultProgressDetails.vue
- src/components/widgets/WidgetProgressHistory/WidgetProgressHistory.vue
- src/styles/main.scss
- src/styles/typography.scss
- src/views/Item/ItemMeasurements.vue
- src/views/Item/ItemOKRs.vue
- src/views/KeyResultHome.vue
- src/views/ObjectiveHome.vue
* TODO: Re-structure/-design the add value form
> Redesigned key result home

- src/components/forms/KeyResultValueForm.vue
- src/components/modals/KeyResultModal.vue
- src/views/KeyResultHome.vue
> Add reusable key result value form

- CHANGELOG.md
- src/components/DashboardPeriodSelector.vue
- src/components/modals/EditGoalsModal.vue
- src/components/modals/KPIProgressModal.vue
- src/components/modals/ProgressModal.vue
- src/components/widgets/WidgetsKPIHome.vue
- src/locale/i18n.js
- src/views/ItemAdmin/ItemAdminPeriod.vue
- src/views/KpiHome.vue
There are some pre-existing issues with the `KPIHome` range filter. Fixed separately.
> Configure flatpickr locale globally

- CHANGELOG.md
- src/components/DashboardPeriodSelector.vue
- src/components/Navigation/ItemTabBar.vue
- src/config/periods.js
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/views/Item/ItemMeasurements.vue
> Move the period selector to a more prominent position

- .github/workflows/validate-openapi.yml
Depends on https://github.com/oslokommune/okr-tracker/pull/661.
> Add GitHub Action for validating the OpenAPI spec

- CHANGELOG.md
- src/components/DashboardPeriodSelector.vue
- src/components/Navigation/ItemTabBar.vue
- src/styles/main.scss
> Responsive item tab bar

- src/components/ActionBar.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/store/index.js
- src/views/Item/ItemOKRs.vue
Open up the OKR timeline view (Gantt chart) as a feature preview for super admins.
> Open up the OKR timeline view for super admins

- src/components/GanttChart.vue
Make goals in the Gantt chart clickable like they are in the table view.
> Make goals in the Gantt chart clickable

- CHANGELOG.md
- src/components/IndicatorTooltip.vue
- src/styles/_tooltip.scss
Align the tooltip styling better with the style that is used in the line chart comment tooltips (which in turn aligns better with the Punkt design language).
> Align tooltip styling with chart tooltips

- CHANGELOG.md
- src/components/Navigation/ItemTabBar.vue
- src/components/PeriodSelector.vue
- src/components/widgets/WidgetWeights.vue
- src/router/router-guards/itemMeasurements.js
- src/views/Item/ItemOKRs.vue
Move the OKR period selection tabs into a drop down menu in the top bar matching the period selector on the KPI page.
> Move OKR period selector to the top bar

- src/components/GanttChart.vue
Support displaying objectives without periods in the Gantt chart.
> Support objectives without periods in Gantt chart

- src/views/ItemAdmin/ItemAdminKeyResult.vue
Fix the display of error/success messages when testing a Google Sheets integration for key results.
> Fix KR Google Sheets integration messages

- CHANGELOG.md
- src/components/Navigation/SiteHeader.vue
Fix centering of the top bar text on pages where there's no logged in user.
> Fix top bar content centering

- CHANGELOG.md
- index.html
- src/components/ItemRow.vue
- src/components/KeyResultProgressDetails.vue
- src/components/KeyResultRow.vue
- src/components/Navigation/SiteSidebar.vue
- src/components/ObjectiveRow.vue
- src/components/RoleMembers.vue
- src/components/TabList.vue
- src/components/UserProfileMenu.vue
- src/components/modals/EditGoalsModal.vue
- src/components/modals/ProfileModal.vue
- src/components/widgets/PeriodTrendTag.vue
- src/components/widgets/WidgetKpiCard/WidgetKpiCard.vue
- src/components/widgets/WidgetKpiProgressStats.vue
- src/styles/_buttons.scss
- src/styles/_forms.scss
- src/styles/_modal.scss
- src/styles/main.scss
- src/styles/typography.scss
- src/views/Admin/components/AdminItems.vue
- src/views/Home.vue
- src/views/Item/ItemAbout.vue
- src/views/ItemAdmin/ItemAdminKPI.vue
- src/views/ItemAdmin/ItemAdminOKRs.vue
- src/views/KeyResultHome.vue
- src/views/Login.vue
Load Punkt's `typography` module and adjust our existing styling accordingly.
> Use Punkt's typography module

- package-lock.json
- package.json
Upgrade `firebase-tools` to version 12, mainly to be able to upgrade vulnerable sub-dependencies.
> Upgrade to `firebase-tools` 12.x

- src/util/LineChart/index.js
Regression introduced in 7263eb1a124d7f5ca8eb87c90e9b8df2e6fa2377.
> Fix formatting of line chart tooltips

- CHANGELOG.md
- src/components/RoleMembers.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/styles/typography.scss
- src/views/Item/ItemAbout.vue
Depends on ~~https://github.com/oslokommune/okr-tracker/pull/722~~.
> Revamp the about page

- src/components/Navigation/toolbar/PeriodSelector.vue
- src/util/okr.js
- src/views/Item/ItemOKRs.vue
Enable the dynamic date picker on the OKR overview page, temporarily only for super admins.
> Show date picker for OKRs for super admins

- src/views/Item/ItemAbout.vue
Temporarily hide the team member listing to see if anybody misses it.
> Hide the team member listing

- src/components/generic/form/buttons/BtnBase.vue
- src/styles/_buttons.scss
- src/views/Admin/components/AdminAccessRequests.vue
- src/views/ItemAdmin/ItemAdminKPIs.vue
Replace the previous "ghost" buttons with secondary buttons from Punkt.
> Use Punkt button component for ghost buttons

- src/components/ArchivedRestore.vue
- src/components/forms/KpiAdminForm.vue
- src/components/generic/form/buttons/BtnBase.vue
- src/components/widgets/WidgetProgressHistory/ProgressHistoryTable.vue
- src/styles/_buttons.scss
- src/styles/main.scss
- src/views/Login.vue
- src/views/RequestAccess.vue
Use the Punkt button component for all secondary buttons.
> Use Punkt button component for secondary buttons

- src/components/GanttChart.vue
Regression introduced in 78fb429664d9d999d071f145ba16bf1f55e8367c.
> Fix today indicator styling in the timeline chart

- CHANGELOG.md
- functions/util/defaultPreferences.js
- src/components/ActionBar.vue
- src/components/KeyResultRow.vue
- src/components/ProgressBar.vue
- src/db/User/defaultPreferences.js
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/store/index.js
- src/views/Item/ItemOKRs.vue
- src/views/KeyResultHome.vue
- src/views/ObjectiveHome.vue
Merge the compact and detailed objective views into a common "list" view. Make timeline the default view.
> Merge the compact and detailed OKR views

- package-lock.json
- package.json
Upgrade `eslint` to get rid of its dependency on the vulnerable `word-wrap` module.
> Upgrade `eslint`

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/KpiDetails.vue
- src/components/KpiWidgetGroup.vue
- src/components/widgets/WidgetKpiCard/WidgetKpiCard.vue
- src/util/kpiHelpers.js
- src/views/ItemAdmin/ItemAdminKPIs.vue
Obs: Forsiktig med å teste denne på en release channel, siden den fort muterer databasen. :sweat_smile:
> Support drag & drop reordering of measurements

- src/views/ObjectiveHome.vue
Replace brittle and less efficient watchers with a computed property.
> Replace brittle watchers with a computed property

- src/views/Admin/components/AdminItems.vue
- src/views/Admin/components/AdminUsers.vue
Replace Font Awesome icons on the admin page with relatively suitable Punkt replacements.
> Punkt-ify icons on the admin page

- functions/package-lock.json
Apply `npm audit fix` in in `/functions` to address security issues that don't require special attention.
> Apply `npm audit fix` in `/functions`

- CHANGELOG.md
- src/components/modals/KPIProgressModal.vue
Fix error when editing integer measurement progress values.
> Fix error when editing measurement progress values

- src/components/modals/KPIProgressModal.vue
A couple of fix-ups after 53da4f360219de5dd469ce3287363827a442b79b.
> Further measurement modal fixes

- public/help.md
Update the help page after the recent changes on how periods work.
> Bring help page up to speed

- src/components/GanttChart.vue
- src/components/OkrLinkCard.vue
- src/components/ProgressBar.vue
> Respect objective period length for cards in the timeline

- CHANGELOG.md
- src/components/drawers/EditItemDrawer.vue
- src/components/drawers/EditKeyResult.vue
- src/components/drawers/EditObjective.vue
- src/components/forms/KpiAdminForm.vue
- src/components/generic/form/FormSection.vue
- src/config/validation.js
- src/main.js
Validation in forms are now less "eager" and errors are only displayed after attempted form submissions.
> Make form validation less eager

- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
Remove translation string that is unused as of 9a923b7cb7d43d186900e4dbae41b84e934e4fc6.
> Remove unused translation string

- src/components/period/PeriodSelector.vue
- src/styles/_reset.scss
- src/styles/main.scss
- src/views/Admin/components/AdminItems.vue
- src/views/Admin/components/AdminUsers.vue
Include the whole Punkt CSS module. Remove some of our own unnecessary resets and make some additional tweaks that became necessary after loading all of Punkt.
> Go all in on Punkt

- src/components/EmptyState.vue
- src/components/GanttChart.vue
- src/components/KeyResultLinkCard.vue
- src/components/ProgressBar.vue
- src/components/panes/KeyResultPane.vue
- src/components/panes/ObjectivePane.vue
- src/styles/main.scss
> Color coded objectives and key results

- src/components/KeyResultValuesList.vue
- src/components/ObjectiveLinkCard.vue
- src/components/modals/ProgressModal.vue
- src/components/panes/KeyResultPane.vue
- src/components/panes/ObjectivePane.vue
- src/styles/main.scss
- src/util/format.js
- src/util/index.js
> Pane design adjustments

- src/components/panes/KeyResultPane.vue
- src/util/LineChart/linechart-helpers.js
- src/util/LineChart/symbols.js
> Move key result progress graph to pane header card

- CHANGELOG.md
- firebase.json
Set more security headers: `Content-Security-Policy`, `Referrer-Policy`, `X-Content-Type-Options`, and `X-Frame-Options`.
> Set more security headers

- src/components/GanttChart.vue
- src/components/KeyResultLinkCard.vue
- src/components/ProgressBar.vue
- src/components/panes/KeyResultPane.vue
- src/components/panes/ObjectivePane.vue
- src/components/panes/WorkbenchPane.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/util/index.js
> More progressbar indicators

- src/components/ObjectiveDetailsCard.vue
- src/components/panes/ObjectivePane.vue
- src/locale/locales/nb-NO.json
> Simplified details view in objective pane

- src/components/drawers/EditKeyResult.vue
- src/locale/locales/nb-NO.json
- src/styles/_vSelect.scss
Also disable owner dropdown when archiving key results.
> Disable key result owner select on archive

- CHANGELOG.md
- src/components/KpiDetails.vue
- src/components/KpiWidgetGroup.vue
- src/components/KpiWidgetGroupLink.vue
- src/components/Navigation/toolbar/PeriodSelectorMenu.vue
- src/components/Navigation/toolbar/ViewToggle.vue
- src/components/panes/TimelinePane.vue
- src/components/widgets/PeriodTrendTag.vue
- src/components/widgets/WidgetKpiCard/WidgetKpiCard.vue
- src/components/widgets/WidgetKpiProgressGraph.vue
- src/components/widgets/WidgetKpiProgressStats.vue
- src/components/widgets/WidgetProgressHistory/WidgetKpiProgressHistory.vue
- src/config/periods.js
- src/router/router-guards/itemMeasurements.js
- src/router/router-guards/itemOKRs.js
- src/store/index.js
- src/store/modules/kpis.js
- src/store/modules/okrs.js
- src/views/Item/ItemMeasurements.vue
- src/views/Item/ItemOKRs.vue
Depends on https://github.com/oslokommune/okr-tracker/pull/919
> Desynchronize selected period for OKRs and KPIs

- CHANGELOG.md
- src/components/GanttChart.vue
- src/components/ObjectiveLinkCard.vue
- src/components/drawers/EditObjective.vue
- src/components/panes/ObjectivePane.vue
- src/components/panes/TimelinePane.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
- src/store/index.js
- src/store/modules/okrs.js
- src/views/Item/ItemOKRs.vue
> Keep "ghost" objectives visible in the timeline until closed

- CHANGELOG.md
- src/components/GanttChart.vue
- src/components/ObjectiveLinkCard.vue
- src/config/periods.js
Also set the default OKR period to "all".
> Dim objectives outside the period

- CHANGELOG.md
- src/components/FormComponent.vue
- src/components/drawers/EditKeyResult.vue
- src/components/drawers/EditObjective.vue
- src/locale/locales/en-US.json
- src/locale/locales/nb-NO.json
* Allow lifting when creating new objectives.
* Added some more help texts to owner selection for both objectives and key results.
> Revised objective lift flow

- CHANGELOG.md
- src/components/KeyResultLinkCard.vue
- src/components/KpiWidgetGroup.vue
- src/components/panes/ObjectivePane.vue
- src/components/widgets/WidgetKpiCard/WidgetKpiCard.vue
Restrict dragging to the handle (drag icon).
> Fix drag and drop of measurements and key results on mobile

- src/components/ApiClientCard.vue
- src/components/drawers/EditItemDrawer.vue
- src/components/drawers/EditKeyResult.vue
- src/components/drawers/EditObjective.vue
- src/components/drawers/KpiDrawer.vue
- src/components/generic/form/buttons/BtnCancel.vue
- src/components/generic/form/buttons/BtnDelete.vue
- src/components/generic/form/buttons/BtnSave.vue
- src/views/Admin/CreateDepartment.vue
- src/views/Admin/CreateOrganization.vue
- src/views/Admin/CreateProduct.vue
- src/views/Admin/components/AddUsers.vue
- src/views/RequestAccess.vue
Update `BtnSave`, `BtnDelete` and `BtnCancel` to provide a similar interface as `PktButton`.
> Align button components with Punkt

- src/components/KeyResultValuesList.vue
- src/components/ObjectiveDetailsCard.vue
- src/components/panes/KeyResultPane.vue
Same border width as Punkt `Messagebox`/`Alert`.
> Use same border color for panel cards

- functions/package-lock.json
- functions/package.json
Upgrade `firebase-functions` to be able to upgrade the vulnerable `firebase-admin` later.
> Upgrade `firebase-functions`

- .github/workflows/deploy-prod.yml
- .github/workflows/test.yml
- CHANGELOG.md
- README.md
- functions/package-lock.json
- functions/package.json
- package-lock.json
- package.json
Upgrade to the Node.js 20 (LTS) runtime for Cloud Functions, local scripts, and GitHub Actions.
> Upgrade to Node.js 20 (LTS)

- index.html
- public/loader.svg
- src/components/AppLayout.vue
- src/router/index.js
- src/store/tracker.js
- src/views/Item/ItemWrapper.vue
Display a spinner until the app is completely loaded. Hopefully fixes FOUC issues on Firefox.
> Improve page load feedback (spinner)
