oslokommune/okr-tracker

package-lock.json, package.json, src/components/IconComment.vue, src/components/IconGraph.vue, src/components/IndicatorTooltip.vue, src/styles/_tooltip.scss, src/util/LineChart/index.js, src/util/LineChart/linechart-helpers.js, src/util/LineChart/symbols.js
Adds tooltips triggered by either hover or click on data points in graph. Allows for optional drawing of comment symbol for values that may be accompanied by a comment (in the future). Likely cleaner ways to do this with D3!? 😅 
TODO: 
* Format value in tooltip depending on type.
* Decide where comments should "live".
=> Add tooltips to graph

.eslintrc.js
The previous config resulted in the following error message:
Configuration for rule "operator-assignment" is invalid:
Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"never"').
Specify the severity to stop it from complaining.
=> Fix ESLint `operator-assignment` rule config

src/components/DashboardResultIndicatorsSection.vue
"So far this year" extended until the end of the current year, leaving much of the graph blank (especially early in the year). Make it end at the current date instead, giving more screen estate to real data.
=> Make "so far this year" end at the current date

src/components/modals/AddKPIModal.vue, src/locale/locales/en-US.json, src/locale/locales/nb-NO.json, src/styles/_forms.scss, src/styles/main.scss, src/styles/ods/ods-hr.scss, src/util/kpiHelpers.js, src/views/ItemAdmin/ItemAdminKPI.vue
Add a new KPI type choice in the KPI add and edit forms.
The background on the KPI add modal is not optimal right now together with ODS components, but that will be fixed separately.
=> Support choosing KPI type

src/components/DashboardPeriodSelector.vue
=> Fix period selector rendering on Safari

.eslintrc.js
Operator assignments are already used in some places throughout the code, so this rule has been causing noise for some time.
=> Drop `operator-assignment` rule to silence ESLint

src/components/DashboardResultIndicatorsSection.vue, src/util/LineChart/index.js
The line chart height is now `450` for the dashboard while defaulting to `350` (affects the tracker, KPI/KR).
=> Increase line chart height for dashboard and tracker

src/components/DashboardResultIndicatorsSection.vue, src/locale/locales/en-US.json, src/locale/locales/nb-NO.json, src/util/LineChart/index.js, src/util/LineChart/linechart-helpers.js
`LineChart.render` now supports a `target` property which accepts a list of "targets", e.g populated from a future KPI subcollection `targets`. In addition, an optional legend is drawn to the graph.
```js
targets: [
{ value: 0.6, startDate: new Date('2022-03-01'), endDate: new Date('2022-08-01') },
{ value: 0.75, startDate: new Date('2022-09-01'), endDate: new Date('2022-12-01') },
]
```
=> Initial support for graph target line and legend

functions/api/helpers.js
This should apply both to the existing POST-endpoint and the new PUT-endpoint.
=> Keep comments when updating KPI progression values using the API

src/components/UserProfileMenu.vue, src/components/generic/form/buttons/Btn.vue, src/components/generic/form/buttons/BtnDelete.vue, src/components/generic/form/buttons/BtnSave.vue, src/components/generic/form/buttons/index.js, src/components/modals/AddKPIModal.vue, src/components/modals/KPIProgressModal.vue, src/components/modals/KeyResultModal.vue, src/components/modals/ProfileModal.vue, src/components/modals/ProgressModal.vue, src/components/widgets/WidgetProgressHistory/WidgetProgressHistory.vue, src/locale/locales/en-US.json, src/locale/locales/nb-NO.json, src/styles/_buttons.scss, src/views/Admin/components/EditUser.vue, src/views/ItemAdmin/ItemAdminGeneral.vue, src/views/ItemAdmin/ItemAdminKPI.vue, src/views/ItemAdmin/ItemAdminKeyResult.vue, src/views/ItemAdmin/ItemAdminObjective.vue, src/views/ItemAdmin/ItemAdminPeriod.vue, src/views/KeyResultHome.vue
A lot of files changed, but mostly repeated edits except the components themselves 😉 
* Add some basic, reusable button components
* Align style and interaction for (all) form buttons, e.g. a confirm popover for all delete buttons
=> Reusable form buttons

src/locale/locales/nb-NO.json
Use the Norwegian spelling of dashboard, "dashbord", in the Norwegian translation.
=> Fix Norwegian spelling of dashboard

src/util/LineChart/index.js
Fix a bug where the lowest value in a progression was prepended and plotted as the first value in line charts.
=> Fix line chart value plotting bug

src/components/ItemRow.vue
Text in the front page item rows could overflow and be clipped. Fix this by allowing the text to grow to normal line height, but reduce the padding instead to retain the previous amount of air (ish).
=> Fix text clipping in front page rows

src/util/kpiHelpers.js
```
1.1 => 1,1
1.19 => 1,19
1.9 => 1,9
1.9999 => 2
1.989 => 1,99
1.9899 => 1,99
1.333 => 1,33
1.337 => 1,34
1.989999999 => 1,99
123 => 123
123456 => 123 456
1234561231 => 1 234 561 231
1999999 => 1 999 999
123456.33333 => 123 456,33
123456.99999 => 123 457
27.9204761905 => 27,92
27.9294761905 => 27,93
```
=> Use fixed-point formatting for KPIs

src/util/LineChart/index.js
Don't let line chart paddings turn the y axis start value from positive to negative.
=> Don't pad past zero

src/components/DashboardResultIndicatorsSection.vue
* Progress data fetching should hopefully be triggered less often.
* Save queries by depending on `currentValue` from the KPI object being updated.
* ~~TODO: Since `all` now is the default period (T#314), consider adding a loading state indicator while fetching data.~~
* ~~(This will cause conflicts with https://github.com/oslokommune/okr-tracker/pull/499 - will await merge, and rebase.)~~
=> Dashboard RI component refactor

src/components/DashboardResultIndicatorsSection.vue
Revert a part of 787e7b4a7ca0033e75b7a088a1efd1c881118092 causing line charts to be rendered twice, which results in losing the transition animation between graphs.
=> Avoid double chart rendering

firestore.rules
Protect the `superAdmin` field from being written by users other than super admins.
=> Protect `superAdmin`

README.md, functions/api/helpers.js, functions/api/index.js, functions/api/routes/kpi.js, functions/api/routes/status.js, public/openapi/v1.3.0.yaml, src/views/Api.vue
Adds the following new API endpoints:
* `GET /kpi` - list all KPIs, with a couple of additional properties (`updateFrequency`, `isStale`)
* `GET /stats`- return some app "metrics", for now different KPI counts
=> Add status endpoint to API for KPI monitoring

.github/workflows/codeql-analysis.yml, .github/workflows/main.yml, contributing.md
The `develop` and `master` branches are obsoleted in favor of a single `main` branch.
=> Switch default branch to `main`

functions/index.js, functions/kpi/progress/handleKpiProgress.js, functions/kpi/progress/index.js, src/components/DashboardResultIndicatorsSection.vue, src/util/LineChart/index.js, src/views/KpiHome.vue
Speed up KPI progress plots by caching the progression as a JSON blob directly on the KPI Firestore document. Firestore isn't too happy about retrieving thousands of documents (like is typically needed from the `progression` sub collection).
=> Speed up KPI progress plots

src/components/widgets/WidgetsItemHomeRight.vue, src/components/widgets/WidgetsMobile.vue
Fix the infamous "activePeriod is null" bug when navigating back to the item home back from a sub-page.
=> Fix `activePeriod` bug

src/components/widgets/WidgetsItemHomeRight.vue
Hide only the progression wheel if there is no progression, not the entire right column.
=> Show right column even if there is no progression

firebase.json
MacOS Ventura uses 5000 (!) for some Airplay server thing. And 7777 for 3rd party identity services.
How to test: Run `npm run dev` and check that the emulator starts.
=> Change emulator ports 5000 and 7777 that crash with MacOS Ventura

src/locale/locales/en-US.json, src/locale/locales/nb-NO.json
Tweak the KPI help text to make it clearer that manual and automatic updates aren't mutually exclusive. Also fix a typo in the Norwegian version.
=> Tweak KPI help text

src/components/modals/EditGoalsModal.vue
Make the Return button in the goal editing dialogue save the current goal instead of deleting it.
=> Make Return in goal dialogue save, not delete

src/components/modals/ModalWrapper.vue
Disable closing modals by clicking outside them. This to prevent accidental closing of modals that might contain unsaved changes in forms. It is still possible to close by using the escape key or the dedicated close button.
=> Disable closing modals by outside click

functions/index.js, functions/kpi/index.js, src/views/ItemAdmin/ItemAdminKPI.vue
Remove the function that triggered on KPI updates due to an infinite loop with our progress updating function.
This is intended as an emergency fix. It caused the Google Sheet integration checking for KPIs to disappear when KPIs are saved, but that will be fixed later (for instance by adding a separate button for checking the connection, like we have for key results).
=> Remove trigger on KPI updates

functions/index.js, functions/kpi/index.js, src/components/forms/KpiAdminForm.vue, src/views/ItemAdmin/ItemAdminKPI.vue
Restore the functionality for testing a Google Sheets connection when saving a KPI by making an explicit test call instead of relying on the previous (removed) KPI update trigger.
=> Restore Google Sheets testing functionality

src/components/FormComponent.vue, src/components/ProgressUpdateAPIExample.vue, src/components/forms/KpiAdminForm.vue, src/components/modals/KPIProgressModal.vue, src/components/modals/ModalWrapper.vue, src/components/modals/ProgressModal.vue, src/locale/locales/en-US.json, src/locale/locales/nb-NO.json, src/views/ItemAdmin/ItemAdminKeyResult.vue
Move the progress API example from the KPI creation page to the dialogue where progression values are registered. Also align it with the example for key result progression by generalizing the functionality into a component that can be used in both places.
=> Revamp the progress API example

.github/workflows/deploy-prod.yml, .github/workflows/test.yml, CHANGELOG.md, README.md, functions/package-lock.json, functions/package.json, package-lock.json, package.json
Upgrade to the Node 16 runtime for Cloud Functions, local scripts, and GitHub Actions.
The Cloud Functions should probably be updated piecewise and carefully since the previous attempt failed (see Trello card).
=> Upgrade to Node 16

src/components/modals/KPIProgressModal.vue
Limit the precision of displayed measurement values to avoid JavaScript floating point precision errors.
=> Limit precision of measurement value display

CHANGELOG.md, src/components/ItemRow.vue, src/components/KeyResultRow.vue, src/components/ProgressBar.vue, src/locale/locales/en-US.json, src/locale/locales/nb-NO.json, src/views/KeyResultHome.vue
Improve the progress bar styling to better differentiate between the empty and filled states. The new style is currently only used on the front page since it works best on a light background, but over time we should converge on that style everywhere.
The internals of the `ProgressBar` component have also been changed to render an actual `<progress>` element instead of a `<div>`.
=> Improve progress bar styling

CHANGELOG.md, src/components/IndicatorTooltip.vue, src/views/KeyResultHome.vue
* The y axis still defaults to specified `startValue`/`targetValue`.
* Includes minor visual improvements to the graph (height and padding).
* Tooltip also enabled for values and comments.
=> Adaptive y axis for the key result line chart

src/components/GanttChart.vue, src/locale/locales/en-US.json, src/locale/locales/nb-NO.json, src/util/format.js, src/util/index.js
Add a basic version of a Gantt chart display of objectives.
The `gantt-wip` branch can be used to test the component.
=> Add basic Gantt chart component

package-lock.json, package.json
Upgrade `firebase-tools`, mainly to be able to upgrade its vulnerable `http-cache-semantics` dependency.
Fixes https://github.com/oslokommune/okr-tracker/security/dependabot/86.
=> Bump `firebase-tools`

src/router/index.js, src/router/router-guards/index.js, src/router/router-guards/itemCommon.js, src/router/router-guards/itemMeasurements.js, src/views/Item/ItemWrapper.vue
Clean up the router, mainly by preventing `itemHome` (now named `itemCommon`) from running twice in some routes.
The logic in `itemHome` (now `itemCommon`) intended to prevent it from running twice was also flawed, since `next()` doesn't actually cause the function to return.
=> Clean up the router a tad

CHANGELOG.md, src/components/widgets/WidgetKpiFilter.vue, src/components/widgets/WidgetProgressHistory/WidgetProgressHistory.vue, src/locale/locales/en-US.json, src/locale/locales/nb-NO.json, src/views/KpiHome.vue
Don't have the date picker on the KPI details page disappear even if there are no measurements in the selected period.
=> Fix disappearing date picker on KPI details page

firestore.indexes.json, src/components/widgets/WidgetWeights.vue, src/store/actions/set_active_period_and_data.js, src/util/okr.js, src/views/Item/ItemOKRs.vue
Support listing objectives without a `period` reference, but that rather have `startDate` and `endDate` set directly on themselves.
=> Support listing objectives without period

package-lock.json, package.json, src/views/Api.vue, vite.config.js
Upgrade to Vue 2.7, the "current, and final minor release of Vue 2.x". There seems to be an [issue with building `swagger-ui`](https://github.com/swagger-api/swagger-ui/issues/7918) with later versions of Vite(?). More or less temporary fix by using [`swagger-ui-dist`](https://www.npmjs.com/package/swagger-ui-dist), but open to that not being an actual solution.
* https://v2.vuejs.org/lts/
* https://v2.vuejs.org/v2/guide/migration-vue-2-7.html#Vite
=> Upgrade to `vue@2.7`

src/util/okr.js
The previous check didn't hold when periods overlap; objectives could then be deemed to belong to multiple periods.
=> Check actual period reference instead of dates

firebase.json
Declare a codebase in the Firebase functions config. This makes it possible to have functions spread across different codebases deploy to the same Firebase project without deleting all the unknown functions.
=> Declare Firebase functions codebase

public/openapi.yaml
This should have been done in 63d8bad8be8449c7656d7dc1d1c87633874e0304, but was forgotten.
=> Bump the OpenAPI spec version

CHANGELOG.md, src/components/GanttChart.vue, src/components/ObjectiveRow.vue, src/views/Item/ItemOKRs.vue
Align the Gantt chart design better by aligning the objective boxes with the compact and detailed views by reusing the `ObjectiveRow` component.
The team tag is removed for now, since it only causes noise as long as goals belong to only one team at the time.
=> Align Gantt chart design better

src/util/PieChart/index.js, src/util/PieChart/pie-helpers.js
Simplify the pie chart component by removing its (unused) dark mode option.
=> Remove dark mode support from pie chart component

src/components/ObjectiveRow.vue
Flex the objective row instead of using grid to get rid of the spacer element and to get a simpler implementation overall.
=> Flex the objective row

CHANGELOG.md, src/components/forms/KpiAdminForm.vue, src/components/widgets/WidgetKpiCard/MiniGraph.vue, src/components/widgets/WidgetKpiCard/WidgetKpiCard.vue, src/components/widgets/WidgetKpiProgressGraph.vue, src/locale/locales/en-US.json, src/locale/locales/nb-NO.json, src/util/kpiHelpers.js, src/views/ItemAdmin/ItemAdminKPIs.vue
Start y-axes in measurement graphs counting from zero by default. Make it possible to revert individual measurements to the old behavior of starting the y-axis around the lowest measured value in the measurement admin settings.
=> Support adjustable measurement y-axis start values

CHANGELOG.md, src/views/RequestAccess.vue
Fix a bug that makes pressing Enter on the access request page clear the form instead of submitting it.
=> Don't clear request access form on Enter

CHANGELOG.md, src/components/forms/KpiAdminForm.vue
Use zero as the default start value for existing measurements in addition to new ones.
=> Use zero as start value for existing measurements

CHANGELOG.md, src/components/AppLayout.vue, src/components/Navigation/ItemTabBar.vue, src/components/Navigation/SiteHeader.vue, src/styles/main.scss, src/views/ItemAdmin/ItemAdminKPI.vue, src/views/ItemAdmin/ItemAdminKPIs.vue
Don't use `position: sticky` for the main header bars as it messes with scroll position handling. It also makes the scroll bar overlap the headers.
Depends on ~~https://github.com/oslokommune/okr-tracker/pull/716~~.
=> Unstick the header bars

.github/workflows/codeql-analysis.yml, .github/workflows/deploy-prod.yml, .github/workflows/test.yml, .github/workflows/validate-openapi.yml
Upgrade GitHub Actions workflows that were running on deprecated Node 12 runtimes.
Pin all actions to commit hashes instead of tags while we're at it since tags are mutable and pose a security threat.
=> Upgrade GitHub Actions workflows from Node 12

src/components/widgets/WidgetKeyResultDetails.vue, src/components/widgets/WidgetObjectiveDetails.vue, src/router/router-guards/keyResultHome.js, src/store/actions/set_active_key_result.js, src/util/format.js, src/util/okr.js, src/views/Item/ItemOKRs.vue
Fix the key result page when the key result belongs to an objective without a period reference.
Also show the period on the detail pages for objectives without period references, just like we do for those with periods.
=> Fix display of KRs for periodless objectives

src/components/FormComponent.vue, src/styles/_forms.scss
The button is now also styled by Punkt. ~~Depends on https://github.com/oslokommune/okr-tracker/pull/701~~.
=> Move copy button inside copiable input control

CHANGELOG.md, src/components/widgets/WidgetKpiCard/MiniGraph.vue, src/components/widgets/WidgetKpiProgressGraph.vue
The lock on 100% on the y-axis for measurements made it difficult to see changes in measurements that use a small part of the scale.
Percentage measurements that use the full part of the scale are displayed like before.
=> Remove measurement target values special treatment

CHANGELOG.md, src/components/Navigation/navbar/NavMenuItem.vue
Not really sure what is going on here, other than something messing up event handling when dynamically updating the `name` prop on the `PktIcon` component (which watches this prop and uses `v-html`). The event itself seems to be captured by `@click`, but the template is not updating. Not even sure how [preventing propagation](https://v2.vuejs.org/v2/guide/events.html#Event-Modifiers) on the parent is a workaround 🤷
=> Fix event handling for nav menu toggle icons

CHANGELOG.md, src/components/Navigation/header/OrganizationSelector.vue
When `PktIcons` are dynamically updated (which uses the [`v-html`](https://v2.vuejs.org/v2/api/#v-html) directive to render its contents), the clicked SVG element is somehow no longer detected by [vue-click-outside](https://github.com/vue-bulma/click-outside/tree/master) as a child element (`el.contains`) ... or something. 
This is a quick-fix, pretty hackish, and the problem is likely to reappear at some point.
=> Fix (another) navbar event bug

CHANGELOG.md, src/components/GanttChart.vue, src/components/widgets/WidgetKeyResultDetails.vue, src/components/widgets/WidgetObjectiveDetails.vue, src/util/okr.js, src/views/Item/ItemOKRs.vue
Always display all objectives in the timeline view. Make the period selector put a specified period in focus by centering and highlighting it instead of filtering the objectives.
=> Center and highlight selected periods in timeline

src/components/drawers/EditKeyResult.vue
Make it possible to move past the first step in the key result edit dialogue without changing the key result's name or description.
=> Fix first step in key result edit dialogue

src/components/GanttChart.vue
The `ObjectiveRow` component already sets the `objective` class on its top level element.
=> Remove duplicate `objective` class

CHANGELOG.md, src/components/widgets/WidgetKpiProgressGraph.vue, src/components/widgets/WidgetProgressHistory/ProgressHistoryTable.vue
Reorder the date and value columns in progress tables (both on the web pages and in the CSV exports) so that the date comes first.
=> Reorder date and value in progress tables

CHANGELOG.md, src/components/pages/NotFoundPage.vue, src/locale/locales/en-US.json, src/locale/locales/nb-NO.json, src/router/index.js, src/router/router-guards/itemCommon.js, src/router/router-guards/itemMeasurements.js, src/router/router-guards/objectiveHome.js, src/router/router-guards/routerGuardUtil.js, src/store/actions/set_active_key_result.js, src/views/Item/ItemMeasurements.vue, src/views/Item/ItemWrapper.vue, src/views/KeyResultHome.vue, src/views/NotFound.vue, src/views/ObjectiveHome.vue
Improve "not found" handling by not redirecting to a dedicated `/404` route anymore. Handle not found documents locally instead, which gives the opportunity for more intelligent/local error pages.
Also add a catchall "not found" page for paths that don't match any route.
=> Improve "not found" handling

.github/workflows/deploy-prod.yml, .github/workflows/test.yml, CHANGELOG.md, README.md, functions/package-lock.json, functions/package.json, package-lock.json, package.json
Drop support for Node.js 16 which is reaching its end of life soon and upgrade to the Node.js 18 (LTS) runtime for Cloud Functions, local scripts, and GitHub Actions.
=> Upgrade to Node.js 18 (LTS)

CHANGELOG.md, src/components/drawers/EditObjective.vue, src/views/Item/ItemOKRs.vue
Add a shortcut to quickly select the last used period when creating a new objective.
=> Add period shortcut when creating a new objective

src/components/GanttChart.vue
Fix centering of period in the timeline view after the new loading state was implemented.
=> Fix centering of period in the timeline view

src/components/ObjectiveRow.vue
Display chevrons in objective links in the timeline view pane when multiple objectives are selected as well.
=> Always display chevrons in objective links

src/components/KeyResultsList.vue, src/components/ObjectiveWorkbench.vue, src/components/drawers/EditKeyResult.vue, src/components/widgets/WidgetWeights.vue, src/store/actions/set_active_period_and_data.js, src/store/index.js, src/views/Item/ItemOKRs.vue, src/views/ObjectiveHome.vue
Remove key results from the global store to make them easier to work with (and start uncluttering the cursed `set_active_period_and_data` action).
They are now loaded on-demand instead according to the objectives they belong to. This also makes it easier to load key results belonging to others, since they're no longer loaded based on `parent`, but on `objective`.
=> Remove key results from the global store

src/components/drawers/EditKeyResult.vue, src/util/getActiveItemType.js, src/views/Item/ItemAbout.vue
Add `isOrganization` util function, a sister function to the existing `isDepartment`, and use both functions more consistently throughout.
Salvaged from https://github.com/oslokommune/okr-tracker/pull/842.
=> Add item type util

firestore.rules, src/store/actions/set_active_period_and_data.js, src/store/index.js
Load external objectives (objectives that the current item are "contributors" to (as per a new `objectiveContributors` table)) in the timeline view.
There is currently no way to create `objectiveContributors` entries in the web UI, but this lays the groundwork for it.
Depends on ~~https://github.com/oslokommune/okr-tracker/pull/836~~.
=> Load external objectives in the timeline view

CHANGELOG.md, firestore.rules
Fix several bugs in the `isAdminOfParent` Firestore rule check to make organization admins able to create/edit/delete items within their organizations (again?).
=> Fix create/edit/delete rights for org admins

firestore.rules, src/db/ObjectiveContributors/ObjectiveContributors.js, src/db/ObjectiveContributors/index.js, src/db/ObjectiveContributors/props.js
Add create and remove functions for the new objective contributors collection.
=> Add objective contributors create/remove functions

src/util/LineChart/index.js
Possibly a bit clearer to the user (?) with the added bonus of circumventing issues caused by non-limited KPI-titles.
=> Simplify graph legend for measurements

CHANGELOG.md, src/main.js
This fixes an XSS issue because the v-tooltip library is rendering HTML by default.
=> Don't render HTML in tooltips

CHANGELOG.md, src/components/drawers/EditKeyResult.vue, src/locale/locales/en-US.json, src/locale/locales/nb-NO.json
Give new key results a start value of 0, a target value of 100, and percentage as unit of measurement by default.
=> Improve key result defaults

functions/backend/utils/collectionUtils/DomainWhitelistCollection.js, functions/backend/utils/handleAccessRequests.js
Disregard leading and trailing whitespace in both input email and whitelisted domains to make the check more robust against unintentionally added whitespace.
=> Disregard whitespace in whitelist check

src/components/KpiWidgetGroup.vue, src/components/panes/ObjectivePane.vue
Make tweaks to the drag and drop styling:
- Slow down the animation a tad.
- Make the placeholder ("ghost") totally gray.
- Hide the border things in the key results list for the ghost element.
=> Make tweaks to the drag and drop styling

CHANGELOG.md, src/views/Item/ItemAbout.vue
Reintroduce the team member listing on the about page, but only for members of the same organization.
=> Reintroduce team member listing on the about page

package-lock.json, package.json
Upgrade Vite to fix recent hot reloading errors along the lines of:
```
ReferenceError: can't access lexical declaration '[...]' before initialization
[hmr] Failed to reload [...]. This could be due to syntax errors or importing non-existent modules. (see errors above)
```
=> Upgrade Vite to fix hot reloading

CHANGELOG.md, src/components/HTMLOutput.vue
Fix Markdown rendering of descriptions on objective, key result, and measurement detail pages.
=> Fix Markdown rendering in descriptions

src/components/RoleMembers.vue
When adding a new member to a team, the team member list is rendered several times before settling. The user attributes are missing on the first render, so take that into account in the display name computation.
=> Fix display name computation in team member list

src/store/index.js
Remove useless conditional check (`user` would always evaluate to `true`; it is checked earlier in the same function).
=> Fix CodeQL warning about useless conditional

firestore.rules, tests/firebase/firestore.test.js
Make users able to create objective contributors for objectives on their item's parent item (🤯).
=> More objective contributors Firestore rule tweaks

src/components/GanttChart.vue
* Fix `scrollIntoView` in Chrome (Mac only?) when selecting objectives in the timeline. Tested in Vivaldi, Chrome and FF (Mac) + Vivaldi (Windows).
* Do not select any objective by default when adding all period objectives to the workbench. This might feel unexpected. (Only _replace_ any already active objective if it is not part of the period selection. This also avoids a redundant navigation error which would occur otherwise.)
=> Timeline interaction fixes

src/components/drawers/EditKeyResult.vue, src/components/drawers/EditObjective.vue, src/util/objectiveContributors.js
Synchronize the objective contributor links when an objective is lifted, as the links may be needed to keep the donor as a contributor after the lift.
=> Sync objective contributors on objective lift

functions/index.js, functions/progress/handleKeyResultProgress.js, functions/progress/index.js
Don't attempt to update legacy period progression on objective updates anymore, as objectives are decoupled from their legacy periods automatically when they're updated now, making the update fail.
=> Fix period progression update error

CHANGELOG.md, src/util/LineChart/index.js
=> Fix overlapping x-axis dates on small screens

CHANGELOG.md, package-lock.json, package.json
Upgrade to `firebase-tools` to version 13 to lose two vulnerable sub-dependencies: `tough-cookie` and `request`.
=> Upgrade to `firebase-tools` 13

CHANGELOG.md, functions/backupAndRestore.js
Don't catch exceptions that arise in the backup and restore functions, otherwise GCP won't properly interpret them as errors.
=> Don't catch exceptions in backup/restore functions

CHANGELOG.md, src/db/User/User.js
Organization admins aren't allowed to write the field `superAdmin` for security reasons, so creating new users with `superAdmin: false` would fail even though it's `false`. Just don't write that field at all.
=> Fix bug preventing org. admins to add new users

CHANGELOG.md, functions/kpi/progress/handleKpiProgress.js
Long comments were clogging up the JSON cache (Firestore has a limit of 1 MB per document). Cropping the comments down to 500 characters should push this problem many years into the future.
=> Fix plotting of measurements with long comments

src/components/modals/ModalWrapper.vue, src/styles/_modal.scss, src/views/Admin/components/AdminItems.vue, src/views/Admin/components/ArchivedItemModal.vue, src/views/Admin/components/ItemList.vue
Currently, archived items cannot be edited through the admin panel because this involves redirecting the users to a "non-existent" item page. This issue exists in the current version as well.
This PR introduces a modal that prompts the user to restore the selected item before redirecting them to the item edit drawer.
=> Add modal for restoring items from admin panel

src/components/KpiWidgetGroup.vue, src/components/panes/ObjectivePane.vue, src/util/kpiHelpers.js
Attempt to fix drag-n-drop ordering of key results and KPIs using batch writes. This to prevent Vuefire subscription updates causing conflicts.
=> Fix drag-n-drop ordering for KRs and KPIs

src/components/GanttChart.vue, src/components/ObjectiveLinkCard.vue, src/components/panes/ObjectivePane.vue, src/composables/gantt.js, src/store/okrs.js
There is still a (mostly) visual snag when adding the first objective with an item's parent as the owner. This happens because the objective is initially created with the currently active item as its parent and first updated with the correct parent later, triggering consecutive subscription updates. I don’t remember why it was originally implemented this way. Maybe fix separately if prioritized.
=> Improve handling of timeline ghosts

CHANGELOG.md, package-lock.json, package.json
Upgrade from Vite 5 to 6 to be able to upgrade its vulnerable esbuild dependency later.
=> Upgrade to Vite 6
